/**
 * @file bb_client.h
 * @author Rajesh Kumar (rajesh.kumar01@addverb.com)
 * @brief Formulation of the client class
 * which is responsible for communication
 * with the lower level
 * @version 0.1
 * @date 2023-07-14
 *
 * @copyright Copyright (c) 2023
 *
 */
#ifndef BB_CLIENT_H_
#define BB_CLIENT_H_

#include "lower_level_interface.h"
#include "bb_configs.h"
#include "rate.h"
#include "utils.h"
#include "socket_send_exception.h"
#include "socket_connect_exception.h"
#include "error_manager.h"

#include <thread>
#include <chrono>
#include <math.h>

#include <arpa/inet.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
#include <stdint.h>
#include <thread>
#include <mutex>
#include <vector>
#include <atomic>
#include <memory>
#include <cmath>
#include <csignal>
#include <iostream>

/**
 * @brief Tx packed structure to be
 * received from the beaglebone
 *
 */
typedef struct
{
    double pos[6] = {0,0,0,0,0,0};
    double vel[6] = {0,0,0,0,0,0};
    double torque[6] = {0,0,0,0,0,0};
    double bottom_imu[3] = {0,0,0};
    double top_imu[3] = {0,0,0};
    double combined_angles[3] = {0,0,0};
    bool gpio_input[2] = {0,0};
    double vbus = 0;
    double current = 0;
    double vshunt = 0;
    unsigned int error_code[4] = {0,0,0,0};


} __attribute__((__packed__)) Tx;

/**
 * @brief Rx packed structure to be
 * written to the beaglebone
 *
 */
typedef struct
{
    int mode = 2;
    double pos[6] = {0,0,0,0,0,0};
    double vel[6] = {0,0,0,0,0,0};
    double torque[6] = {0,0,0,0,0,0};

} __attribute__((__packed__)) Rx;

/**
 * @brief Class to implement the gimbal implementation
 * as part of the tcp ip model
 * @todo : No watch dog on this end; is this good ?
 * @todo : Add the rate class here
 */
class BBClient : public LowerLevelInterface
{

public:
    // empty constructor
    BBClient() { working_ = false; };

    // empty destructor
    ~BBClient()
    {
        if (worker_.joinable())
        {
            worker_.join();
        }
    };


    // function to read data from requisite lower level - should run in a separate thread
    AddMotion::DeviceData readDataLL();

    // function to write velocity commands to requisite lower level - should run in a separate thread
    bool writeDataLL(const AddMotion::ControlOutput &);

    // function to initialize requisite lower level - should run in a separate thread
    bool setup(const AddMotion::InitializationConfig &);

    // stop the lower level
    bool stopLL();

    // start the lower level
    bool startLL();

    // description of the error code generated by the lower level
    int getError();

private:

    // start the read write worker thread
    void startWorker_();

    // implement the while loop here
    void work_();

    // values to be swapped in the input
    void swapValues_(AddMotion::DeviceData &input);

    // swap back to the writing
    void writeSwapValues_(AddMotion::ControlOutput &output);

    // write the velocity output after doing the required conversions if any
    void writeVel_(const AddMotion::ControlOutput &write);

    // write the position output after doing the required conversions
    // if any
    void writePos_(const AddMotion::ControlOutput &write);

    // write the torque output
    void writeTor_(const AddMotion::ControlOutput &write);

    // convert the position by the desired offset if required
    double convertPos_(const double &, const int &index);

    // convert the velocity by the desired offset if required
    double convertVel_(const double &, int index);

    // convert the torque by the desried offset if required
    double convertTor_(const double &, int);

    // convert the angular position from lower level to readable form 
    Eigen::VectorXd convertAngular_(); 

    // wrapper method for socket send with possible errors handled
    ssize_t bb_send_(int sockfd, const void *buf, size_t len, int flags);

    // wrapper method for socket connect with error handling
    ssize_t bb_connect_(int sockfd, const sockaddr *addr, socklen_t len);

    // sigpipe error-check callback method
    static void sigpipeHandler_(int code);

    // frame to be transmitted
    Rx tx_frame_;

    // frame to be read
    Tx rx_frame_;

    // server address
    struct sockaddr_in server_addr_;

    // sockfd required to send and receive the data
    int sock_fd_;

    // base positions to add to the system
    std::vector<double> base_pos_;

    // factor 
    std::vector<double> fac_;

    // implementation of the worker thread
    std::thread worker_;

    // flag to check whether the engine is working or not
    std::atomic<bool> working_;

    // mutex for read and write implementation
    std::mutex mut_;

    // pointer to the rate class 
    std::unique_ptr<Rate> rate_;

    // angular pose offset 
    Eigen::Matrix<double,3,1> ang_offset_;

    // kinematic offset 
    std::vector<double> kin_offset_;
};

#endif