/**
 * @file lower_level_interface.hpp
 * @author Rajesh Kumar (rajesh.kumar01@addverb.com)
 * @brief Implementation of the Lower level interface 
 * @version 0.1
 * @date 2023-07-14
 * 
 * @copyright Copyright (c) 2023
 * 
 */

#ifndef LOWER_LEVEL_INTERFACE_H_
#define LOWER_LEVEL_INTERFACE_H_

#include <memory>
#include <eigen3/Eigen/Core>
#include <thread>

#include "read_write.h"

/**
 * @brief implementation of the lower level interface : 
 * for read and write implementation of the lower level class 
 * 
 */
class LowerLevelInterface
{
    
    public:


    virtual ~LowerLevelInterface() {};

    // function to read data from requisite lower level - should run in a separate thread 
    virtual AddMotion::DeviceData readDataLL() = 0;

    // function to write velocity commands to requisite lower level - should run in a separate thread 
    virtual bool writeDataLL(const AddMotion::ControlOutput &) = 0;

    // function to initialize requisite lower level - should run in a separate thread 
    virtual bool setup(const AddMotion::InitializationConfig &) = 0;

    // stop the lower level 
    virtual bool stopLL() = 0;

    // start the lower level 
    virtual bool startLL() = 0; 

    // description of the error code generated by the lower level 
    virtual int getError() = 0; 


};


#endif